### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#737] opened 2017-01-19 12:19 UTC
Some of these points were raised by @wasamasa in a previous version of this repo, but I had to delete it to make the issue migration work. (Sorry to everyone who watched and starred the previous one.) So here we go again.

Yes, this is intended to be an official evil repo. To do:

- [x] Migrate hg to git
- [x] Migrate issues
- [x] Convert the wiki front page at https://bitbucket.org/lyro/evil/wiki/Home to markdown and commit it as README.md. (#738)
- [x] Announce the move. We need help from @lyro here, probably it would be good to put a note on https://bitbucket.org/lyro/evil/wiki/Home linking here and a notification to the mailing list. [Done, see https://lists.ourproject.org/pipermail/implementations-list/2017-January/002250.html]
- [x] Point the MELPA recipe to this repo (what about marmalade?)
- [ ] Find a place to discuss (#evil or #emacs-evil on freenode, gitter?). When porting the readme, seems the channel #evil-mode is mentioned there, as well as a mailing list.

I have invited @syl20bnr, @bmag and @wasamasa as members for the moment. I'm willing to take the role as lead maintainer, but the idea was to have a team that could pull the ropes collectively. I would like to ask that nobody merge their own PRs (unless trivial). Evil does not have quite the traffic of Spacemacs, but it's not negligible.

In time I hope we can offer a stable environment for other evil-xyz packages in need of maintenance help as well.

There are eight open PRs on bitbucket. I think that's few enough that we can deal with them manually, maybe ask the authors to resubmit here. (One of them is mine.)

Input is welcome.

**Comment by wasamasa** [comment] 2017-01-19 13:20
First of all, thanks for initiating this!  As announced on Reddit, I intend to take care of things Evil depends upon, the most important one being the goto-chg package (which is rotting away on EmacsWiki and keeps us from having Evil installable on MELPA Stable).  I'd like to put it under this organization after clarifying its status with the author who IIRC showed himself cooperative.  Once that's done, I'll finally be able to resolve https://github.com/melpa/melpa/pull/2262 and https://github.com/melpa/melpa/issues/2813.

As for other things I can help out with, I'd like to dig through open issues on the bug tracker and fix valid/close invalid issues to further understand Evil's codebase and get a better idea where we are currently.  The only problem with that is that the original reporters were on Bitbucket, so getting in touch with them might be impossible if they don't happen to be on GitHub or offer any other way of getting back in touch with them.

Regarding IRC, we'll have to ask `#freenode` what channel name is OK as `#evil` was registered over a decade ago and doesn't appear to have anything to do with the project while `#evil-mode` was never registered, but suggested as official channel in the README.

The development model sounds good to me for the purpose of maintenance.  It might be inadequate for the implementation of big, new features, but we'll have to put up a roadmap first to see what is desired.  I'd imagine a list of official Vim features showing their implementation state in Evil and started one myself for [eyebrowse](https://github.com/wasamasa/eyebrowse): [evil.org](https://github.com/wasamasa/eyebrowse/blob/master/evil.org).

**Comment by ninrod** [comment] 2017-01-19 13:24
@TheBB thanks for organizing this. About Marmalade, it's been given me 500 bad gateway for a while. Seems rather unmantained and not used much.

**Comment by TheBB** [comment] 2017-01-19 13:50
@wasamasa getting goto-chg here and on MELPA stable would be (y).

**Comment by therockmandolinist** [comment] 2017-01-19 19:04
>In time I hope we can offer a stable environment for other evil-xyz packages in need of maintenance help as well.

@TheBB For future reference, three such packages are [evil-leader](https://github.com/cofi/evil-leader), [evil-numbers](https://github.com/cofi/evil-numbers), and [evil-indent-textobject](https://github.com/cofi/evil-indent-textobject), the first two of which I think are fairly highly used. All were maintained by @cofi but have remained untouched for at least a couple years.

For evil-numbers, I've implemented a couple of fixes (padding, block select, last number in region not being affected) on my fork, and others have done the same or requested for added features in pull requests.

**Comment by TheBB** [comment] 2017-01-19 19:39
Yes sounds like all the @cofi packages are abandoned and have been forked. I have a fork of evil-indent-textobject myself. Spacemacs has moved to a different implementation of the leader functionality as well.

**Comment by therockmandolinist** [comment] 2017-01-19 20:44
@TheBB any chance of the spacemacs implementation of leader functionality becoming its own package? I don't use spacemacs myself, but I do really like the leader system it has going on (and in particular, `set-leader-keys-for-minor-mode`)

**Comment by ninrod** [comment] 2017-01-19 20:51
@therockmandolinist, it is already a separate package: https://github.com/justbur/emacs-bind-map

**Comment by TheBB** [comment] 2017-01-24 10:44
So all the boxes are checked now, except the discussion place.

**Comment by ninrod** [comment] 2017-01-24 12:03
gitter is pretty good. the spacemacs channel on gitter is a huge success from what I can tell.

**Comment by GordonGustafson** [comment] 2017-01-24 14:41
> As for other things I can help out with, I'd like to dig through open issues on the bug tracker and fix valid/close invalid issues to further understand Evil's codebase and get a better idea where we are currently.

If I want to pitch in, should I add comments with the appropriate course of action? I'd like to close #409 as no-repro and close #513 as an effective duplicate of #610 (or vice-versa), but I don't have the permissions.

**Comment by TheBB** [comment] 2017-01-24 14:45
Yes, please feel free. I'll go ahead and deal with the ones you mentioned.

**Comment by jojojames** [comment] 2017-01-24 22:50
+1 evil discussion on freenode

**Comment by wasamasa** [comment] 2017-01-24 23:05
I'm obviously for keeping it to Freenode because it just seems wrong for open-source projects.  That aside, people already knowing the `#emacs` channel expect a related channel on Freenode, from experience sending spacemacs newbies there off to gitter doesn't sit right with them either as it introduces an extra hoop to jump through.  Hence why I'm all in for `#evil-mode` to become the place for coordinating developer discussion.  And yes, I'm already waiting for you there.

**Comment by expez** [comment] 2017-01-25 12:31
I just saw the move.  I'd be willing to be part of the team of maintainers if more help is wanted.

I'm already maintaining https://github.com/expez/evil-smartparens and am a member of the https://github.com/clojure-emacs organization, for the intersection of all things clojure and emacs.

**Comment by TheBB** [comment] 2017-01-25 13:29
Help would be welcome! At the moment the biggest problem I think we have is that the tests are failing on Emacs 25, more info on that in https://github.com/emacs-evil/evil/issues/731. If anyone can figure out a good workaround for this I'd be very happy.

**Comment by dunn** [comment] 2017-01-27 16:55
One more thing; could the previous releases be tagged on this repo?

**Comment by wasamasa** [comment] 2017-02-08 12:27
@dunn It seems as if the sources contain empty commits for versions, but tags weren't migrated over.  Could you please open a new ticket for this where we can discuss how to fix this properly?

**Comment by dunn** [comment] 2017-02-08 18:35
@wasamasa looks like #458 is where that should take place?

**Comment by wasamasa** [comment] 2017-02-08 19:34
@dunn Well, indeed, but it looks like tags were recreated meanwhile.  Thanks for bringing this to our attention!

**Comment by Benaiah** [comment] 2017-02-09 04:05
Just read through the backlog of /r/emacs and found out that evil's maintainer situation has been resolved with this new repo. That's awesome! I'd like to start contributing, perhaps first doing documentation (I'm pretty experienced with elisp but not with evil's internals). Is there anywhere else notable that could use some work, other than just going through the issue list?

Additionally, would anyone be interested in me building a static website for Evil to be hosted on Github Pages? I'm thinking something fairly simple, probably a single page.

Thanks to the new maintainers for their work getting this taken care of. You'll likely see me on #evil-mode soon.

**Comment by wasamasa** [comment] 2017-02-09 08:45
@benaiah Currently there is no roadmap or even list of known problems, other than the issue tracker, efforts to create one are most welcome.

Regarding documentation of internals, Evil does it much like Emacs core does, by having a bit of information in the official manual and more substantial comment blocks in its files.  The main difficulty I've found in understanding its codebase is the high level of abstraction.  Merely studying the sources doesn't reveal everything, you'll need to inspect its state as well to completely understand it.  There are lots of macros that manipulate initially empty variables that are consulted at a later point in time to determine the behavior of other commands...

I like the idea of a more welcoming website than just the repo README, however I'm not sure how much more benefit it would provide.  Could you please outline the contents you'd like to put there?

**Comment by TheBB** [comment] 2017-02-09 09:21
Now that the tests are passing again, I'd like to make a new release soonish.

**Comment by bmag** [comment] 2017-02-19 11:35
Hey all, I've been preoccupied the following month, but I'm here now. I won't have much time to dedicate to Evil, but I will try to fix bugs in Evil or other evil-xyz packages. Did we agree on a discussion place?

**Comment by wasamasa** [comment] 2017-02-19 12:03
@bmag I've registered #evil-mode on Freenode as the channel has been around since forever, but hasn't been registered yet.

**Closed** 2017-03-08 20:41 UTC
