### ISSUE TITLE
Evil macro recorded `oo` characters don't match the ones that end up in the register

### ISSUE THREAD

**Issue by Invertisment** [emacs-evil/evil#1788] opened 2023-04-29 10:38 UTC
# Issue type
- Bug report

When recording and replaying macro `foofoofoo` I sometimes get `foofoofoo` but other times I get `foofooofooo`.

See issue https://github.com/syl20bnr/spacemacs/issues/15457
We already did some digging and it's probably the macro recorder. 
I don't want to paste everything here and I think it's best if you'd go and read the issue in the link.

Currently I moved on from Spacemacs and I only register this one so that it would be fixed.

# Environment
Currently I don't have this emacs distribution but it has to reoccur in the newest versions.

**Comment by tomdl89** [comment] 2023-05-18 08:32
That's a pretty long thread, so I may have missed something, but it looks like this was reproducible _without_ using evil? I can't reproduce it at all, so I'm inclined to close this unless someone can provide repro instructions that work for me.

**Comment by Invertisment** [comment] 2023-05-18 11:19
So you tried both and neither was the problem?
It wasn't consistent in our case too. So I don't know how to consistently reproduce it. Maybe it got fixed.
We could reopen it if it comes back.

**Comment by tomdl89** [comment] 2023-05-18 11:28
Yeah, I couldn't repro with evil nor with kmacro fns directly. I'll close for now, but more than happy to reopen if anyone can provide steps which specifically require evil to be involved, and I can replicate on some version of emacs.

**Closed by tomdl89** 2023-05-18 11:28 UTC
