### ISSUE TITLE
"." behavior differs from vim

### ISSUE THREAD

**Issue by jemfinch** [emacs-evil/evil#745] opened 2017-01-25 17:15 UTC
In vim:

i123456789<ESC>0
4x.

Results in the buffer contents being "9".

In evil-mode this results in the buffer contents being "6789".  The '.' repeats the 'x', not the '4x'.

**Comment by TheBB** [comment] 2017-01-25 17:18
Yes, we know. Duplicate of https://github.com/emacs-evil/evil/issues/731

**Closed by TheBB** 2017-01-25 17:18 UTC
