### ISSUE TITLE
`evil-ex-global` extremely slow

### ISSUE THREAD

**Issue by Alexander-Shukaev** [emacs-evil/evil#1120] opened 2019-01-18 13:56 UTC
# Issue type
- Question

Before opening any issue, I would like to ask the community whether they also feel that `evil-ex-global` is extremely slow.  For instance, if I do `g/<pattern>/kill-whole-line` on a medium-size (below 10 MB) file (which also does not contain extremely long lines), I have to wait for several minutes for that operation to complete.  I don't know the exact reason but I can at least continuously see the `Garbage collecting...done` message in the minibuffer, where the `done` part is continuously flickering (I guess it's a hint that there is progress).  Whether its because of GC or something else is yet to be determined but invoking GC that often might potentially be the problem.  I will try to collect more information from profiler but in the meantime, please share your experiences.

**Comment by dzop** [comment] 2019-02-23 00:21
I think this has to do with `kill-whole-line` rather than `evil-ex-global`. With some initial testing I'm seeing over 60% GC time with `kill-region` being the cause of most of the garbage when doing `g/<pattern>/kill-whole-line` on an 8.8 MB file.

Also, just removing the `eval` line below makes `evil-ex-global` finish in around 1s which is another hint that it is the command being run.

https://github.com/emacs-evil/evil/blob/297b8f323754d967beeaed28080311f5afbe25c8/evil-commands.el#L3627

**Comment by Alexander-Shukaev** [comment] 2019-02-23 20:58
Interesting, I guess this is definitely something for <kbd>M-x</kbd> `report-emacs-bug`.

**Comment by dzop** [comment] 2019-02-23 21:15
Actually a much more fair comparison would be to replace `eval` with

```emacs-lisp
(cl-letf (((symbol-function #'kill-whole-line) #'ignore))
   (eval command-form))
``` 

since `command-form` is actually a call to `evil-ex-call-command`. With this `evil-ex-global` still finishes within a second or two.

**Comment by Alexander-Shukaev** [comment] 2019-02-23 21:48
I also tried with `evil-delete` instead and it worked just fine.  This is definitely a problem of `kill-whole-line`.  How can such a core vanilla function be so inefficient?!

**Comment by dzop** [comment] 2019-02-24 00:55
Playing around with this some more: the issue seems to be the stuff around the `kill-new` call in `kill-append` which causes the slow down. `kill-whole-line` eventually calls `kill-append` which concatenates the current kill with the string being appended, so it concatenates all of the lines killed so far with a new line while `g/<pattern>/kill-whole-line` is being evaluated. This `concat` call and replacing the head of the `kill-ring` with the concatenated string is probably what is invoking the GC so much.

**Comment by Alexander-Shukaev** [comment] 2019-12-04 03:11
Something to follow up with Emacs mailing list.

**Comment by axelf4** [comment] 2023-01-16 10:28
Closing as the quadratic time behavior from `kill-append` `concat`:ing each matched line individually seems inevitable when using `kill-whole-line` with `:global`.

**Closed by axelf4** 2023-01-16 10:28 UTC
