### ISSUE TITLE
numeric delete backward characters

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [emacs-evil/evil#962] opened 2017-11-07 14:28 UTC
# Issue type

- Enhancement request

# Environment

Emacs version: 25.3
Operating System: osx
Evil version: latest version
Evil installation type: MELPA
Graphical/Terminal: Graphical

# Reproduction steps
- Start Emacs
- type `5x` in normal mode

# Expected behavior

delete 5 backward characters

# Actual behavior

only delete one backward character

**Comment by edkolev** [comment] 2017-11-07 15:56
Hey, could you do this:
- try to reproduce with clean emacs + evil (clone this repo, run `make emacs` which will start a fresh emacs with nothing but evil)
- check what the `x` key is bound to

I can't reproduce BTW

**Comment by wasamasa** [comment] 2017-11-07 17:10
Why did you delete the line about the repro in `make emacs`? I mean, I sure can tell you didn't bother, but why not be honest and just put no there?

This issue doesn't make any sense. `x` doesn't delete backwards in Vim, so why should it in Evil?  That aside, you didn't provide a proper repro as it's lacking in text to show the expected change, so who knows, maybe you found some edge case, maybe you didn't.  I'm going to close this for now and will reopen once there's more to work with.

**Closed by wasamasa** 2017-11-07 17:10 UTC
Labels: not reproducible

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment] 2017-11-08 07:58
just in my opinion
it is convenient to delete any complex but short string
or part of line with many whitespace
just like "a_string_with_many_similar_characters_but_it_is_easily_counted"
and “part of a line with many whitespace but also is easily counted"

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment] 2017-11-08 08:06
if can provide some useful message, I am glad to work with this

**Comment by wasamasa** [comment] 2017-11-08 17:00
Thanks for the clarification, but my previous point still stands. `x` deletes the *next* character, `6x` will therefore delete the *next* six characters.  If you want to delete backwards, use `X`. If it doesn't behave like you want to in Vim, it's not a bug, just a user error.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment] 2017-11-09 01:28
I think my backward character mean your next character
