### ISSUE TITLE
Pressing o in visual mode does not make the cursor jump to other end of selection

### ISSUE THREAD

**Issue by nikoltoll** [emacs-evil/evil#1116] opened 2019-01-03 15:43 UTC
# Issue type

- Bug report (missing vim feature)
# Environment

Emacs version: GNU/Emacs 24.5.1
Operating System: Windows 7
Evil version: 1.0.7
Evil installation type: manual
Graphical/Terminal: graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)):  No 
# Reproduction steps
- Start Emacs
open a new window
enter insert mode
Type "hello world"
Enter visual mode (Esc, v)
Type 0, then o

# Expected behavior
cursor jumps to end of selection (the end of "world"). This is the behavior in vim.

# Notes
This never seems to have been implemented in previous versions of evil.

**Comment by VanLaser** [comment] 2019-01-03 15:51
Your evil version is really old, maybe try to update the package first? (Using MELPA) Current `:evil-version` on my computer is 1.2.13.

**Comment by ninrod** [comment] 2019-01-03 16:07
cannot reproduce. this is fixed in latest emacs.

**Comment by TheBB** [comment] 2019-01-03 18:00
Closing for reasons already mentioned.

**Closed by TheBB** 2019-01-03 18:00 UTC

**Comment by nikoltoll** [comment] 2019-01-04 10:51
It was a problem with the function evil-sp-override of evil-smartparens, which does not seem to be updated anymore.
