### ISSUE TITLE
Abort macro recording (changed buffer)

### ISSUE THREAD

**Issue by greboide** [emacs-evil/evil#847] opened 2017-06-06 20:36 UTC
function evil-abort-macro is a bug and extremely evil even for evil ;), at the very least this should be configurable and off by default, there is no point in avoiding a macro changing buffer!!!

**Comment by TheBB** [comment] 2017-06-06 20:38
Some details would be appreciated.

**Comment by edkolev** [comment] 2017-06-07 04:50
You can use this doc for guidance on what details are needed https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md

GitHub is supposed to ask you to fill it when opening an issue, please don't ignore it.
If it didn't ask you, maybe there's some bug with how it's set up (typo in the file name or something)

**Comment by greboide** [comment] 2017-06-07 05:42
sure, emacs by default allows us to change buffer when performing a macro, i believe that vim does not has this feature, maybe its a design issue with its macro, maybe its by design. The original author mimicked this vim behavior with this function prohibiting us to change buffer when executing a macro, but there is no purpose on this, besides it uses a poor implementation that hooks on post-command-hook that is not a good practice imho. Emacs has this feature of allowing macros to be able to do pretty much anything i dont think its wise to limit it purposefully. If you like i can write a PR to solve this issue, i even have a variable name to get this option: extremely-evil-abort-macro

**Comment by edkolev** [comment] 2017-06-07 08:02
It took me a while to get it, but I finally did:

Evil aborts macro recording when buffer is changed. Vim doesn't abort, neither does emacs (as far as I understand).

Git blaming shows that the `evil-abort-macro` was added because of this issue https://github.com/emacs-evil/evil/issues/568

**Comment by greboide** [comment] 2017-06-07 15:08
hmm i see, so the original issue was vim macros were being restarted after changing buffers? That is odd behavior, but instead of fixing it they added a workaround that prevents buffer changing, i think this should be properly fixed...

**Comment by greboide** [comment] 2017-06-07 15:09
but just switching off evil macro abort i cant reproduce the original issue...

**Comment by expez** [comment] 2017-09-28 11:58
The following pattern is extremely common and no longer works:

1. Grep for something that needs to be fixed in multiple places
2. Jump to first occurrence
3. Record macro while fixing the problem
4. Ends macro after jumping to next occurrence
5. Inspect next occurrence and conditionally replay the macro or jump again.

The macro recording ends while jumping between the grep buffer and the buffer to modify :/

**Comment by edkolev** [comment] 2017-09-28 15:04
The fix should be quite simple though, someone just needs to carefully remove parts of the code around the `evil-abort-macro` function.

**Comment by edkolev** [comment] 2017-10-06 05:48
#927 is merged, this can be closed.

@greboide please open an issue if you run into unexpected behaviour.

**Closed** 2017-10-28 13:23 UTC
