### ISSUE TITLE
delete-outer-* doesn't match vim's behavior

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#722] opened 2016-10-20 18:35 UTC
Originally reported by: **Nick Felix (Bitbucket: [Dickby](https://bitbucket.org/Dickby), GitHub: [Dickby](https://github.com/Dickby))**

----------------------------------------

with the cursor at `|` pressing `d a B` :
```
#!C
pre;
{
    i|n;
{
post;
```
in evil-mode leaves:
```
#!C
pre;
|
post;
```
but in vim:
```
#!C
pre;
|post;
```

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/722

**Comment by neeasade** [comment] 2017-10-09 13:32
This is not an actual issue and can be closed

**Comment by Dickby** [comment] 2017-10-09 16:36
@neeasade, why do you think it isn't?

**Comment by neeasade** [comment] 2017-10-09 16:45
@Dickby Actually the bug is valid -- I misread the comments on this issue earlier, and was able to reproduce. Apologies.

**Comment by dieggsy** [comment] 2017-10-09 17:05
huh - I think I also misread

**Comment by tomdl89** [comment] 2022-04-18 21:00
I can't reproduce this. Maybe it was fixed in the meantime. Feel free to reopen if you can explain how to repro.

**Closed by tomdl89** 2022-04-18 21:00 UTC
Labels: bug, minor

**Comment by neeasade** [comment] 2022-04-18 21:17
There's a typo in the original issue I see. Should be:

```
#!C
pre;
{
    i|n;
}
post;
```

(where [n] is just used to show the cursor over n)

with vim 8.0, launched with `vim -u NONE`, daB results in:

```
#!C
pre;
|post;
```

while in evil, I get: 

```
#!C
pre;
|
post;
```

I'm not too invested in this issue, idk why I was here in 2017 lol

**Comment by tomdl89** [comment] 2022-04-19 05:47
@neeasade thanks - I should have said, I guessed that was a typo, but still couldn't repro. But I wasn't testing in a vanilla setup. I'll take another look

**Comment by tomdl89** [comment] 2022-04-19 05:57
Nope, still can't repro. Only difference with vim is that `evil-start-of-line` is not respected by evil for this, whereas startofline is in vim (although this is pretty niche, as it's not even documented for vim).

**Comment by tomdl89** [comment] 2022-04-19 06:17
It was fixed in #1578
