### ISSUE TITLE
Switching windows with directional signifier fails when popup window present.

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#676] opened 2016-06-11 00:08 UTC
Originally reported by: **Anonymous**

----------------------------------------

I tend to work with two windows, split vertically. Occasionally if there's a popup helm session or  message in one window I'll end up with a horizontal split in one of the panes -- 3 windows total. If I switch to the unsplit vertical pane (clicking, Ctrl-w w, however) but leave that popup window open, using Ctrl-w + h,j,k,l won't allow me to switch back to split pane with a "No window [right,left,down,up] from selected window" message.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/676

**Comment by axelf4** [comment] 2023-02-01 10:34
Closing this since it is not reproducible, and, as Evil directional window movements just delegate to the built-in windmove library, posting on the Emacs issue tracker would be better.

**Closed by axelf4** 2023-02-01 10:34 UTC
Labels: bug, minor
