### ISSUE TITLE
Please add support for | in line editing

### ISSUE THREAD

**Issue by DarrienG** [emacs-evil/evil#1085] opened 2018-09-05 14:19 UTC
# Issue type

- Enhancement request

# Environment

Emacs version: GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.5.0) of 2018-05-28
Operating System: macOS High Sierra
Evil version: Evil version 1.2.13
Evil installation type: MELPA stable
Graphical/Terminal: Terminal
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
`emacs somefile.c`
`:w|e someotherfile.c`

# Expected behavior
Vim writes the file based on the current buffer name, and then opens a file based on name given after `e`.

https://stackoverflow.com/questions/32943945/what-does-pipe-character-do-in-vim-command-mode-for-example-vimgrep-pattern

# Actual behavior
Rather than running a second command after the `|` it instead writes a file with the name `|e somethotherfile.c`

**Comment by tomdl89** [comment] 2022-04-18 21:11
Duplicate of #584

**Closed by tomdl89** 2022-04-18 21:11 UTC
Labels: enhancement, ex
