### ISSUE TITLE
Support ex's | for chaining commands together

### ISSUE THREAD

**Issue by MyriaCore** [emacs-evil/evil#1362] opened 2020-10-04 21:56 UTC
In vim, `|` allows you to run commands in the `ex` buffer one after another. For example, the following code would print `first` then `second`:

```vim
:echo "first" | echo "second"
" => first
"    second
```

This becomes useful with #1361, because it means that commands that might interpret `|` literally (such as `:normal`) can be circumvented.

**Comment by tomdl89** [comment] 2022-04-18 21:11
Duplicate of #584

**Closed by tomdl89** 2022-04-18 21:11 UTC
