### ISSUE TITLE
evil scroll doesn't respect image 

### ISSUE THREAD

**Issue by millennium-falcon42** [emacs-evil/evil#1137] opened 2019-03-01 11:50 UTC
Evil scrolls takes a image as a single line, regardless of the actual size of the image.

This makes command such as evil scroll scroll too much if an image occupies much (but evil still thinks it's just a single line).

**Comment by dzop** [comment] 2019-03-01 18:14
Duplicate of #1077.

**Closed** 2020-10-08 15:05 UTC
Labels: duplicate
