### ISSUE TITLE
Bug with scrolling when pixel-scroll-precision-mode is enabled

### ISSUE THREAD

**Issue by ashton314** [emacs-evil/evil#1778] opened 2023-04-10 17:24 UTC
# Issue type

- Bug report

Short of it: scrolling up gets stuck when `pixel-scroll-precision-mode` is turned on and Evil is enabled. I can get around it by checking out evil revision `f003ca2`. (Not sure if that's the most recent commit, but there's a good clean starting point.)

# Environment

- Emacs version: GNU Emacs 29.0.90 (build 1, aarch64-apple-darwin22.4.0, NS appkit-2299.50 Version 13.3.1 (Build 22E261)) of 2023-04-10
- Operating System: macOS 13.3.1
- Evil version: 1.15.0 (`master` sometime after `f003ca2` has this issue; `f003ca2` is clean)
- Evil installation type: Elpaca (`master` from source)
- Graphical/Terminal: Graphical
- Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No; used the `--init-directory` from Emacs 29 to get a clean env.

# Reproduction steps
- Create a fresh directory, and put this into a file called `init.el`:

```emacs-lisp
(setq inhibit-startup-screen t)

(defvar elpaca-installer-version 0.3)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil
                              :files (:defaults (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (call-process "git" nil buffer t "clone"
                                       (plist-get order :repo) repo)))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (kill-buffer buffer)
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

;;; ---------------------------- End Elpaca Bootstrap --------------------------------------

;; Install use-package support
(elpaca elpaca-use-package
  ;; Enable :elpaca use-package keyword.
  (elpaca-use-package-mode)
  ;; Assume :elpaca t unless otherwise specified.
  (setq elpaca-use-package-by-default t))

;; Timing
(add-hook 'elpaca-after-init-hook
          (lambda ()
            (message "Emacs loaded in %s with %d garbage collection%s."
                     (format "%.2f seconds"
                             (float-time
                              (time-subtract (current-time) before-init-time)))
                     gcs-done (if (= 1 gcs-done) "" "s"))))

;; Block until current queue processed.
(elpaca-wait)

(pixel-scroll-precision-mode)
(load-theme 'modus-vivendi t)

;; (use-package diminish)

(use-package evil
  :config
  (evil-mode))
```

(The theme isn't strictly necessary, but who likes being blinded by the default white theme, am I right?)

- Fire up Emacs `emacs --init-directory .`
- Wait for Elpaca to install packages from source
- Open e.g. `elpaca/repos/evil/evil-commands.el`—just something with long amounts of text
- Scroll down for a ways, then start scrolling back up. Scroll should get kind of stuck.

# Expected behavior

Scrolling should be as smooth as butter.

# Actual behavior

When the cursor hits the bottom of the screen, it gets stuck: the window will scroll for a bit, then hop back as if the cursor got stuck.

Note that I use a trackpad; I'm not sure if this happens with a scroll wheel.

Screen recording:

https://user-images.githubusercontent.com/2874507/230956163-0612b1c0-67bc-494c-b43d-8c1f0b69e5d2.mov

# Further notes

I am able to work around this by checking out an older version of Emacs:

```emacs-lisp
(use-package evil
  :elpaca (evil :host github :repo "emacs-evil/evil" :ref "f003ca2")
  :config
  (evil-mode))
```

So something introduced since `f003ca2` is causing the problem I think.

**Comment by ashton314** [comment] 2023-05-02 03:15
Looks like I’m not the only one with this issue: https://reddit.com/r/emacs/comments/132gmsp/cursor_seems_to_get_stuck_when_scrolling_need/

**Comment by axelf4** [comment] 2023-06-25 08:52
The regression was bisected to commit d505fec by supahornet. Looking at that commit it seems likely the cause is due to some idiosyncrasy of pixel-scroll-precision-mode.

I am unable to reproduce using GNU Emacs 29.0.92 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0), and so I am closing this. Please comment if the issue persists and I will reopen, though I ask you to first:
* Ensure you are using the latest tagged unstable Emacs version; and
* apply the following patch

  ```diff
  diff --git a/evil-common.el b/evil-common.el
  index bada299..510fb72 100644
  --- a/evil-common.el
  +++ b/evil-common.el
  @@ -995,6 +995,7 @@ (defun evil-adjust-cursor (&optional _)
     "Move point one character back if at the end of a non-empty line.
   This behavior is controlled by `evil-move-beyond-eol'."
     (and (not evil-move-beyond-eol)
  +       (not (bolp))
          (eolp)
          (= (point)
             (save-excursion
  ```

  If that patch fixes the issue then the issue is entirely with pixel-scroll-precision-mode and bug reports should go to its authors instead.

**Closed by axelf4** 2023-06-25 08:52 UTC

**Comment by ashton314** [comment] 2023-06-26 16:42
That patch does the trick!

I'm running the Emacs 29 pre-release. Most current version I think, but I need to check.

I'm not familiar with the internals of `pixel-scroll-precision-mode`—is there any guidance you can give me to send to the mailing list?

Thanks for finding this @axelf4

**Comment by ashton314** [comment] 2023-07-03 16:15
I rebuilt from `emacs-29` branch two days ago; bug seems to have gone away. Thank you very much for looking at this @axelf4 

(For reference, I was using 29.0.90 (build 22e772610a); bug doesn't seem to be with Emacs 29.0.92 (build 22f82))

**Comment by ashton314** [comment] 2023-07-05 19:18
Ugh, I'm getting the bug again without the patch in 29.0.92 from commit c3fefb2b3ae. I'll have to debug this later.
