### ISSUE TITLE
Unknown command when using `-`character with ex command :+1,+2t-1

### ISSUE THREAD

**Issue by syl20bnr** [emacs-evil/evil#919] opened 2017-09-07 14:08 UTC
# Bug report

# Environment

Emacs version: GNU Emacs 25.1.1 (x86_64-apple-darwin16.5.0, NS appkit-1504.82 Version 10.12.4 (Build 16E195)) of 2017-04-20
Operating System: macOS Sierra
Evil version: Evil version evil-git-a496401e
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- in scratch buffer write 10 lines of garbage
- put point on line 1
- enter <kbd>:+1,+2t-1</kbd>

# Expected behavior
Should copy the next two line above point

# Actual behavior
Output unknown command due to the `-` character (the command actually works with <kbd>:+1,+2t1</kbd>)

**Comment by ninrod** [comment] 2017-09-07 21:26
confirmed.

**Comment by wasamasa** [comment] 2017-09-08 15:58
Seems to be the ex parser or rather, its grammar including the dash as permitted character for bindings (which most likely correspond to command identifiers), the quick fix here is to change the `binding` entry in `evil-ex-grammar` to `(binding "[~&*@<>=:]+\\|[[:alpha:]_]+\\|!")`, however this breaks things like `:emacs-version`.  That again can be fixed by extending `evil-ex-parse-command` to include the dash in its check before parsing with the `emacs-binding` entry, I'm not sure though whether this doesn't break anything else.

**Closed** 2019-11-20 10:32 UTC
Labels: bug, ex
