### ISSUE TITLE
evil-20171128.2307 can not initialize in Spacemacs develop

### ISSUE THREAD

**Issue by Anton-Latukha** [emacs-evil/evil#988] opened 2017-11-29 14:13 UTC
# Issue type

- Bug report

# Environment

Emacs version: 25.3.1
Operating System: NixOS 17.09 (2017-11-29 state)
Evil version: evil-20171128.230
Evil installation type: Spacemacs develop ELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
Update Spacemacs develop packages, restart Emacs.
Watch Evil package can not initialize.

# Expected behavior
Nornal initialization of package

# Actual behavior
Spacemacs initialization hangs on Evil.

# Further notes
```
Debugger entered--Lisp error: (error "evil-commands.el:0:0: error: scan-error: (Unbalanced parentheses 123007 167256)")
  signal(error ("evil-commands.el:0:0: error: scan-error: (Unbalanced parentheses 123007 167256)"))
  error("%s:0:0: error: %s: %s" "evil-commands.el" scan-error ("Unbalanced parentheses" 123007 167256))
  autoload-generate-file-autoloads("evil-commands.el" nil "/home/pyro/.emacs.d/elpa/develop/evil-20171128.2307/evil-autoloads.el")
  update-directory-autoloads("/home/pyro/.emacs.d/elpa/develop/evil-20171128.2307")
  package-generate-autoloads(evil "/home/pyro/.emacs.d/elpa/develop/evil-20171128.2307")
  package--make-autoloads-and-stuff([cl-struct-package-desc evil (20171128 2307) "Extensible Vi layer for Emacs." ((emacs (24 1)) (undo-tree (0 6 3)) (goto-chg (1 6)) (cl-lib (0 5))) tar "melpa" nil ((:commit . "620026182c799b511e155d1ea81fe76811134eb6")) nil] "/home/pyro/.emacs.d/elpa/develop/evil-20171128.2307")
  package-unpack([cl-struct-package-desc evil (20171128 2307) "Extensible Vi layer for Emacs." ((emacs (24 1)) (undo-tree (0 6 3)) (goto-chg (1 6)) (cl-lib (0 5))) tar "melpa" nil ((:commit . "620026182c799b511e155d1ea81fe76811134eb6")) nil])
  package-install-from-archive([cl-struct-package-desc evil (20171128 2307) "Extensible Vi layer for Emacs." ((emacs (24 1)) (undo-tree (0 6 3)) (goto-chg (1 6)) (cl-lib (0 5))) tar "melpa" nil ((:commit . "620026182c799b511e155d1ea81fe76811134eb6")) nil])
  mapc(package-install-from-archive ([cl-struct-package-desc evil (20171128 2307) "Extensible Vi layer for Emacs." ((emacs (24 1)) (undo-tree (0 6 3)) (goto-chg (1 6)) (cl-lib (0 5))) tar "melpa" nil ((:commit . "620026182c799b511e155d1ea81fe76811134eb6")) nil]))
  package-download-transaction(([cl-struct-package-desc evil (20171128 2307) "Extensible Vi layer for Emacs." ((emacs (24 1)) (undo-tree (0 6 3)) (goto-chg (1 6)) (cl-lib (0 5))) tar "melpa" nil ((:commit . "620026182c799b511e155d1ea81fe76811134eb6")) nil]))
  #[513 "\302\303\304\"\210\305!\203/
```

**Comment by wasamasa** [comment] 2017-11-29 14:18
This is a duplicate of #987 and has been fixed already.

**Closed by wasamasa** 2017-11-29 14:18 UTC

**Comment by Anton-Latukha** [comment] 2017-11-29 14:19
👍

**Comment by gbuisson** [comment] 2017-11-29 14:21
I'm getting the same issue but using spacemacs master branch.
I'm not sure how to apply the workaround described on #987 with spacemacs.

**Comment by wasamasa** [comment] 2017-11-29 14:26
You should ideally ask the Spacemacs people.  From what I know it incorporates Quelpa, so in theory you should be able to build a newer version of Evil locally instead of waiting for MELPA to publish a new one.
