### ISSUE TITLE
Please recreate release tags for melpa-stable!

### ISSUE THREAD

**Issue by mdorman** [emacs-evil/evil#744] opened 2017-01-25 11:53 UTC
For the moment evil's not available through melpa stable because there are no tags for releases.

**Comment by TheBB** [comment] 2017-01-25 11:55
It won't matter anyway because it has dependencies that aren't on melpa-stable. Once they're there, it'll happen.

Duplicate of https://github.com/emacs-evil/evil/issues/458, see also https://github.com/emacs-evil/evil/issues/737#issuecomment-273774216

**Closed by TheBB** 2017-01-25 11:55 UTC
